require('core.options')
require('core.keymaps')

-- plugins
require('plugins.setup')
require('plugins.theme')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.mason')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.gitsigns')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.formatter')
require('plugins.transparent')
require('plugins.indent-blankline')
require('plugins.noice')
require('plugins.which-key')
require('plugins.dap')
require('plugins.lspsaga')
